### ISSUE TITLE
Invalid value for `steps`, must not be `None`

### ISSUE THREAD

**Issue by nidhinp** [CermakM/argo-client-python#21]
Running the artifacts example code I get the following error.
```
Traceback (most recent call last):
    File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
      response = get_response(request)
    File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
      response = self.process_exception_by_middleware(e, request)
    File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
      response = wrapped_callback(request, *callback_args, **callback_kwargs)
    File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
      return view_func(*args, **kwargs)
    File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
      return self.dispatch(request, *args, **kwargs)
    File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
      response = self.handle_exception(exc)
    File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
      self.raise_uncaught_exception(exc)
    File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
      raise exc
    File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
      response = handler(request, *args, **kwargs)
    File "/app/metoceantrack/modelrun/api/views.py", line 37, in post
      argo_workflow()
    File "/app/metoceantrack/modelrun/api/views.py", line 25, in argo_workflow
      v1alpha1.create_namespaced_workflow(namespace, manifest)
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api/v1alpha1_api.py", line 263, in create_namespaced_workflow
      (data) = self.create_namespaced_workflow_with_http_info(namespace, body, **kwargs)  # noqa: E501
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api/v1alpha1_api.py", line 344, in create_namespaced_workflow_with_http_info
      collection_formats=collection_formats)
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 330, in call_api
      _preload_content, _request_timeout)
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 169, in __call_api
      return_data = self.deserialize(response_data, response_type)
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 241, in deserialize
      return self.__deserialize(data, response_type)
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 280, in __deserialize
      return self.__deserialize_model(data, klass)
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 624, in __deserialize_model
      kwargs[attr] = self.__deserialize(value, attr_type)
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 280, in __deserialize
      return self.__deserialize_model(data, klass)
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 624, in __deserialize_model
      kwargs[attr] = self.__deserialize(value, attr_type)
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 258, in __deserialize
      for sub_data in data]
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 258, in <listcomp>
      for sub_data in data]
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 280, in __deserialize
      return self.__deserialize_model(data, klass)
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 624, in __deserialize_model
      kwargs[attr] = self.__deserialize(value, attr_type)
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 258, in __deserialize
      for sub_data in data]
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 258, in <listcomp>
      for sub_data in data]
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 280, in __deserialize
      return self.__deserialize_model(data, klass)
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 626, in __deserialize_model
      instance = klass(**kwargs)
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/models/v1alpha1_parallel_steps.py", line 47, in __init__
      self.steps = steps
    File "/usr/local/lib/python3.6/site-packages/argo/workflows/client/models/v1alpha1_parallel_steps.py", line 68, in steps
      raise ValueError("Invalid value for `steps`, must not be `None`")  # noqa: E501
  ValueError: Invalid value for `steps`, must not be `None`
```

The example yaml file
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
status: {}
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message
        arguments:
          artifacts:
          # bind message to the hello-art artifact
          # generated by the generate-artifact step
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

  - name: whalesay
    container:
      name: whalesay
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      # generate hello-art artifact from /tmp/hello_world.txt
      # artifacts can be directories as well as files
      - name: hello-art
        path: /tmp/hello_world.txt
  - name: print-message
    inputs:
      artifacts:
      # unpack the message input artifact
      # and put it at /tmp/message
      - name: message
        path: /tmp/message
    container:
      name: print-message
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
```

**Comment by sfc-gh-pkrishnamurthy** [comment]
Hi @nidhinp What you are facing is this: https://github.com/argoproj-labs/argo-client-java/issues/1
and https://github.com/argoproj/argo/issues/2454
Argo-server un-marshalls Parallel steps as an array of steps but swagger believes it should be an object of  type { "steps": [] }

This has been fixed on the master branch but unfortunately has not be released yet. @CermakM Is it on your plan to release the next version soon ?

**Comment by kaushikb11** [comment]
@nidhinp @sfc-gh-pkrishnamurthy Did you guys figure out a fix for this?
